Fix #121 Improve enum support in response example generation.
Rhosys/openapi-explorer pull request #122
Opened 2023-01-13 13:53 UTC by darcyrush

Feel free to modify. Changes are to generate more accurate examples for types other than string;

Example response Model
```
{
    a: string
    b: boolean
    c: number enum            Allowed: 111┃222
    d: email
    e: boolean enum           Allowed: true
    f: date
    g: number
    h: string enum            Allowed: some┃string
}
```

Example response example
```
{
    a: "a"
    b: false
    c: 111
    d: "user@example.com"
    e: true
    f: "2023-01-13"
    g: 0
    h: "some"
}
```

2023-01-13 14:07 UTC, darcyrush commented
I have read the CLA Document and I hereby sign the CLA

2023-01-13 14:08 UTC, darcyrush commented
recheck

2023-01-13 15:29 UTC, wparad commented on src/utils/schema-utils.js
> +    })
```suggestion
    });
```

2023-01-13 15:36 UTC, wparad commented on src/utils/schema-utils.js
> +    ['string', 'number', 'boolean'].forEach(type => {
According to the spec, it has to be a `string`: https://spec.openapis.org/oas/latest.html#serverVariableEnum I'm okay with adding number support here, but it doesn't make sense for boolean, so let's pull that one out.

```suggestion
    ['string', 'number'].forEach(type => {
```

2023-01-13 15:37 UTC, wparad commented on src/styles/schema-styles.js
> +[class$="enum"], .cons, .const { color:var(--yellow); }
There's a bug with the enum css type, we should fix it there instead of here, I'll add a comment with the suggested fix.

2023-01-13 15:41 UTC, wparad requested changes
This is really interesting, while it is against the spec to have this as far as I can see, I don't think it is a bad addition. So let's do it. I've made some small comments, and once they're resolved we should be good to go.

Re: the CLA bot, I believe the bot is complaining that the email on the commit `drush@cbhbank.com` isn't part of your user profile. Haven't seen this problem before. If you don't want to update your profile (or change the commit to be a valid email) that isn't a problem, we can still merge the PR, once the fixes are in.

2023-01-16 07:36 UTC, darcyrush commented
Huh. I didn't realise it wasn't in the spec since I remembered some level of support for it in other generators/viewers. I don't mind if you close this without merging in that case.

Requested changes have been pushed anyway.

2023-01-16 09:55 UTC, wparad commented on src/styles/schema-styles.js
> +[class$="enum"], .cons, .const { color:var(--yellow); }
```suggestion
.enum, .cons, .const { color:var(--yellow); }
```

2023-01-16 09:56 UTC, wparad approved these changes

2023-01-16 09:57 UTC, merged

2023-01-16 10:04 UTC, wparad commented
Available in `0.11.481`