Display descriptions for URL parameters
Rhosys/openapi-explorer pull request #125
Opened 2023-02-10 17:48 UTC by IMSoP

"Parameter Objects" in the OpenAPI spec can include a "description" property, which may include CommonMark formatting: https://spec.openapis.org/oas/latest.html#parameter-object

2023-02-10 18:40 UTC, wparad commented
Interesting, it seems we weren't displaying this, so I appreciate the PR.

I'm looking at the update, and I'm trying to wrap my head around if there is something we can do to improve the UI here. I see that the text in the right cell is off because the new description has `<p>` element:
```html
![image](https://user-images.githubusercontent.com/5056218/218171686-0c7cb705-7dac-4276-bd80-33ae0457c488.png)

2023-02-10 19:22 UTC, wparad commented on src/components/api-request.js
> +              ${param.description
I'm thinking we should swap this up above the `param-constraint` block.

2023-02-10 19:28 UTC, wparad commented on src/styles/api-request-styles.js
> +}
```suggestion
}
.api-request .param-description p {
  margin-block: 0 0.5em;
}
```

2023-02-10 19:29 UTC, wparad requested changes
Two small things and then we should good to merge. If we swap the block order and apply the margin based on my comment, I think this will look much better:

![image](https://user-images.githubusercontent.com/5056218/218180434-c3014086-169c-46a3-8e3b-7ea1898b8b62.png)

2023-02-13 12:02 UTC, IMSoP commented
Yes, I wasn't sure whether it should go above or below the constraints, but testing more, I agree it looks better in the other order. I've applied that and the extra margin rule.

2023-02-13 12:05 UTC, wparad approved these changes

2023-02-13 12:05 UTC, merged

2023-02-13 12:07 UTC, wparad commented
That has been released in version `0.11.487`