Fix api-request leaking state when changing paths.
Rhosys/openapi-explorer pull request #164
Opened 2023-07-14 00:11 UTC by saraid

Reproduction:
1. Given two path items with mutually exclusive sets of mimeTypes,
```js
{ paths: {
  "/foo": {
    "post": {
      "requestBody": {
        "content": {
          "application/octet-stream": {}
        }
      }
    },
    "put": {
      "requestBody": {
        "content": {
          "application/json": {}
        }
      }
    }
  }
}}
```
2. Navigate between them. You'll see errors in the JS console. The UI has no problems.

The error indicates that the `reqBody` is undefined, because it was searching for the incorrect `selectedRequestBodyType` in `requestBodyTypes`. This fix is just patching it so that, if it fails to find the "selected" requestBodyType, it simply picks one that at least exists.

2023-07-14 00:13 UTC, saraid commented
I have read the CLA Document and I hereby sign the CLA

2023-07-14 07:18 UTC, wparad commented on src/components/api-request.js
> +    const reqBody = requestBodyTypes.find(req => req.mimeType === this.selectedRequestBodyType) || requestBodyTypes[0];
I'm not totally sure this is the right fix, the solution seems a bit strange. According to the problem, my guess would be we need to reset the selectedRequestBodyType on route change by watching the input parameters. Or more specifically we could watch `this.request_body` changes and the update the selected value.

2023-07-14 07:20 UTC, wparad requested changes
I believe there might be a better way to handle this. As it is right now, I'm also worried about an infinite loop because we are changing the value of a property that is the one that triggered the function in the first place. I've made a suggestion inline, let me know if you aren't sure how to implement that, and I can go over an example implementation.

2023-07-21 11:56 UTC, merged

2023-07-21 11:57 UTC, wparad commented
Great thank you, this has been merged in #167 to the release `1.0`. If you wait a few hours a version should be released!